services:
  postgres:
    image: postgres:latest
    container_name: gracelinecms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gracelinecms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gracelinecms-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gracelinecms-postgres-data:
